name: GenkiDo
options:
  bundleIdPrefix: ch.budo-team
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"
  developmentLanguage: de

settings:
  base:
    SWIFT_VERSION: "6.0"
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0

targets:
  GenkiDo:
    type: application
    platform: iOS
    sources:
      - GenkiDo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ch.budo-team.GenkiDo
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: X9FHM3F6WK
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSCameraUsageDescription: "GenkiDo benötigt Kamerazugriff um Mahlzeiten zu fotografieren"
        INFOPLIST_KEY_CFBundleDisplayName: GenkiDo
        SWIFT_EMIT_LOC_STRINGS: YES
    entitlements:
      path: GenkiDo/GenkiDo.entitlements
      properties:
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.icloud-container-identifiers:
          - iCloud.ch.budo-team.GenkiDo

  GenkiDoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - GenkiDoTests
    dependencies:
      - target: GenkiDo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ch.budo-team.GenkiDoTests
        GENERATE_INFOPLIST_FILE: YES

  GenkiDoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - GenkiDoUITests
    dependencies:
      - target: GenkiDo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ch.budo-team.GenkiDoUITests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: GenkiDo

schemes:
  GenkiDo:
    build:
      targets:
        GenkiDo: all
        GenkiDoTests: [test]
        GenkiDoUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - GenkiDoTests
        - GenkiDoUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
